# Generated by Django 2.2.1 on 2020-06-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials_kit_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_quantity', models.IntegerField(default=0)),
                ('max_quantity', models.IntegerField(default=0)),
                ('price_per_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Live', 'Live'), ('Closed', 'Closed')], max_length=10)),
                ('closed_date', models.DateTimeField()),
                ('expected_delivery_date', models.DateTimeField()),
                ('users', models.ManyToManyField(to='essentials_kit_management.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Form')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(verbose_name=models.Model)),
                ('delivered_items', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Brand')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Section'),
        ),
        migrations.AddField(
            model_name='brand',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Item'),
        ),
    ]
