# Generated by Django 2.2.1 on 2020-07-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials_kit_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Form')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_cost', models.IntegerField()),
                ('delivered_items', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='form',
        ),
        migrations.RemoveField(
            model_name='sectionitem',
            name='brand_selected',
        ),
        migrations.RemoveField(
            model_name='sectionitem',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='sectionitem',
            name='form',
        ),
        migrations.RemoveField(
            model_name='sectionitem',
            name='quantity_selected',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Form'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Section'),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Brand'),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Item'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Section'),
        ),
    ]
