# Generated by Django 2.2.1 on 2020-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials_kit_management', '0002_auto_20200608_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.CharField(choices=[('DONE', 'Done'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], max_length=10),
        ),
    ]
