# Generated by Django 2.2.1 on 2020-06-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials_kit_management', '0002_auto_20200601_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.CharField(choices=[('Done', 'Done'), ('Live', 'Live'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.IntegerField(default=0)),
                ('quantity_selected', models.IntegerField(default=0)),
                ('brand_selected', models.CharField(default='brand', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Item')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials_kit_management.Section')),
            ],
        ),
    ]
